import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StatusBadge } from "./status-badge";
export const ContainersTable = ({ containers, busyId, onAction, onViewLogs }) => {
    if (!containers.length) {
        return (_jsx("div", { className: "rounded-xl border border-zinc-800 bg-zinc-900 p-6 text-sm text-zinc-300", children: "No containers found." }));
    }
    return (_jsx("div", { className: "overflow-x-auto rounded-xl border border-zinc-800 bg-zinc-900", children: _jsxs("table", { className: "w-full min-w-[720px] text-left text-sm", children: [_jsx("thead", { className: "border-b border-zinc-800 text-zinc-400", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-3 font-medium", children: "Name" }), _jsx("th", { className: "px-4 py-3 font-medium", children: "Image" }), _jsx("th", { className: "px-4 py-3 font-medium", children: "State" }), _jsx("th", { className: "px-4 py-3 font-medium", children: "Status" }), _jsx("th", { className: "px-4 py-3 font-medium", children: "Actions" })] }) }), _jsx("tbody", { children: containers.map((container) => {
                        const isBusy = busyId === container.id;
                        return (_jsxs("tr", { className: "border-b border-zinc-800/70 last:border-0", children: [_jsx("td", { className: "px-4 py-3 text-zinc-100", children: container.name }), _jsx("td", { className: "px-4 py-3 text-zinc-300", children: container.image }), _jsx("td", { className: "px-4 py-3", children: _jsx(StatusBadge, { status: container.status }) }), _jsx("td", { className: "px-4 py-3 text-zinc-400", children: container.statusText }), _jsx("td", { className: "px-4 py-3", children: _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { type: "button", disabled: isBusy, onClick: () => onAction(container.id, "start"), className: "rounded-md border border-zinc-700 px-3 py-1.5 text-zinc-200 hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-60", children: "Start" }), _jsx("button", { type: "button", disabled: isBusy, onClick: () => onAction(container.id, "stop"), className: "rounded-md border border-zinc-700 px-3 py-1.5 text-zinc-200 hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-60", children: "Stop" }), _jsx("button", { type: "button", disabled: isBusy, onClick: () => onAction(container.id, "restart"), className: "rounded-md border border-zinc-700 px-3 py-1.5 text-zinc-200 hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-60", children: "Restart" }), _jsx("button", { type: "button", disabled: isBusy, onClick: () => onViewLogs(container.id), className: "rounded-md border border-zinc-700 px-3 py-1.5 text-zinc-200 hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-60", children: "View logs" })] }) })] }, container.id));
                    }) })] }) }));
};
